### PR TITLE
Bugfix/misc

### PR DESCRIPTION
**Pull request by justy989**

### CODE REVIEW

**Comment by robber-m** [comment]
You bring me pain :(

**Comment by robber-m** [comment]
Lol oops . Meant to approve

**Comment by robber-m** [comment]
Weird. I guess I can't approve?

**Comment by robber-m** [comment]
Maybe because I have a commit in here? Does that mean @ryan is the only one who can approve?

**Comment by justy989** [comment]
wateva, not in a rush, still have some things to do before I move on to the next feature

**Review by ryabouza — APPROVED** [review]

**Pull request merged**
